spring.application.name=notification

spring.datasource.url=jdbc:postgresql://localhost:5432/crm
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=sanjeev
spring.security.user.password=123
